---

- name: "Launch RHEL AMI"
  hosts: localhost
  gather_facts: no

  roles:
  - launch_rhel_ami

- name: "Update {{ ec2_name_prefix }} inventory"
  tower_inventory:
    name: "{{ ec2_name_prefix }} AWS Inventory"
    organization: "Empire"
    state: present
    